//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentsTests.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssignmentsTests.TestData.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (((())))()((((((((())()(()))(()((((()(()(((()((()((()(()()()()()))(((()(()((((((((((())(()()((())()(((())))()(()(()((()(()))(()()()()((()((()(((()()(((((((()()())()((((()()(((((()(())()(())((())()()))()(((((((())(()())(()(((())(()))((())))(()((()())))()())((((())))(()(((((()(())(((()()((()((()((((((((((())(()())))))()))())()()((((()()()()()()((((((())())(((()())()((()()(((()()()))(((((()))(((()(()()()(()(()(((())()))(()(((()((())()(()())())))((()()()(()()(((()))(((()((((()(((((()()(()())((()())())(()((((((( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29x13x26
        ///11x11x14
        ///27x2x5
        ///6x10x13
        ///15x19x10
        ///26x29x15
        ///8x23x6
        ///17x8x26
        ///20x28x3
        ///23x12x24
        ///11x17x3
        ///19x23x28
        ///25x2x25
        ///1x15x3
        ///25x14x4
        ///23x10x23
        ///29x19x7
        ///17x10x13
        ///26x30x4
        ///16x7x16
        ///7x5x27
        ///8x23x6
        ///2x20x2
        ///18x4x24
        ///30x2x26
        ///6x14x23
        ///10x23x9
        ///29x29x22
        ///1x21x14
        ///22x10x13
        ///10x12x10
        ///20x13x11
        ///12x2x14
        ///2x16x29
        ///27x18x26
        ///6x12x20
        ///18x17x8
        ///14x25x1
        ///30x15x22
        ///17x18x7
        ///28x23x24
        ///15x12x25
        ///14x7x20
        ///29x23x8
        ///24x5x22
        ///6x22x8
        ///1x15x26
        ///14x5x1
        ///24x28x28
        ///17x23x23
        ///4x15x7
        ///23x8x11
        ///6x15x1
        ///23x18x13
        ///17x1x26
        ///23x13x17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;^^v^&lt;&gt;v&lt;&lt;&lt;v&lt;v^&gt;&gt;v^^^&lt;v&lt;&gt;^^&gt;&lt;^&lt;&lt;^vv&gt;&gt;&gt;^&lt;&lt;^&gt;&gt;&lt;vv&lt;&lt;v^&lt;^^&gt;&lt;&gt;&gt;&gt;&lt;&gt;v&lt;&gt;&lt;&gt;^^&lt;^^^&lt;&gt;&lt;&gt;&gt;vv&gt;vv&gt;v&lt;&lt;^&gt;v&lt;&gt;^&gt;v&lt;v^&lt;&gt;v&gt;&gt;&lt;&gt;^v&lt;&lt;&lt;&lt;v^vv^&gt;&lt;v&gt;v^&gt;&gt;&gt;vv&gt;v^^^&lt;^^&lt;&gt;&gt;v&lt;^^v&lt;&gt;^&lt;vv^^&lt;^&gt;&lt;&lt;&gt;^&gt;&gt;&lt;^&lt;&gt;&gt;&gt;&lt;&gt;&lt;vv&gt;&lt;&gt;v&lt;&lt;&lt;&gt;&lt;&gt;&lt;&gt;v&gt;&lt;&lt;&gt;^^^^v&gt;&gt;^&gt;^&lt;v&lt;&lt;vv^^&lt;v&lt;^&lt;^&gt;^^v^^^^^v&lt;&gt;&lt;^v&gt;&lt;&lt;&gt;&lt;^v^&gt;v&lt;&lt;&gt;^&lt;&gt;^^v^&lt;&gt;v&lt;v^&gt;v&gt;^^&lt;vv^v&gt;&lt;^&lt;&gt;^v&lt;&gt;&lt;^&gt;&lt;v^&gt;&lt;&gt;&lt;&gt;&lt;&lt;&lt;&lt;&gt;^vv^&gt;^vvvvv&gt;&lt;&gt;&lt;^&lt;vv^v^v&gt;v&lt;&lt;^&lt;^^v^&lt;&gt;^&lt;vv&gt;&lt;v&lt;v^v&lt;&lt;v&lt;&lt;^^&gt;&gt;^^^v^&gt;v&lt;&gt;&lt;^vv&lt;&lt;^&lt;&gt;v&lt;v&gt;&lt;&gt;&lt;v^^&gt;&lt;v&lt;&gt;^^&gt;^^&gt;v^&gt;^&lt;&lt;&lt;&lt;v&gt;&lt;v&lt;&lt;&gt;v....
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yzbqklnj.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rthkunfaakmwmush
        ///qxlnvjguikqcyfzt
        ///sleaoasjspnjctqt
        ///lactpmehuhmzwfjl
        ///bvggvrdgjcspkkyj
        ///nwaceixfiasuzyoz
        ///hsapdhrxlqoiumqw
        ///lsitcmhlehasgejo
        ///hksifrqlsiqkzyex
        ///dfwuxtexmnvjyxqc
        ///iawwfwylyrcbxwak
        ///mamtkmvvaeeifnve
        ///qiqtuihvsaeebjkd
        ///skerkykytazvbupg
        ///kgnxaylpgbdzedoo
        ///plzkdktirhmumcuf
        ///pexcckdvsrahvbop
        ///jpocepxixeqjpigq
        ///vnsvxizubavwrhtc
        ///lqveclebkwnajppk
        ///ikbzllevuwxscogb
        ///xvfmkozbxzfuezjt
        ///ukeazxczeejwoxli
        ///tvtnlwcmhuezwney
        ///hoamfvwwcarfuqro
        ///wkvnmvqllphnsbnf
        ///kiggbamoppmfhmlf
        ///ughbudqakuskbiik
        ///avccmvev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
    }
}
